name: Release

on:
  push:
  release:
    types: [published]

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Api
        run: |
          TOKEN=${{ secrets.DEV_TOKEN }}

          curl \
            -X POST \
            -H "Authorization: token $TOKEN"
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mtshiba/rele/dispatches \
            -d '{"event_type":"release-notification","client_payload":{"msg": "New release published"}}'
